version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: dotnet restore

build:
  project: LearnWithMentor.sln
  verbosity: minimal
  publish_wap: true

artifacts:
 - path: '\LearnWithMentor\bin\Release\netcoreapp2.1\publish'
   name: ServerDeployPackage
   type: WebDeployPackage

deploy:
  - provider: Environment
    name: production
    on:
      branch: master 